apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lwq7jmpln-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lwq7jmpln-go 
  name: lwq7jmpln-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lwq7jmpln-go 
