apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lwq7jmpln-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ab5fee5c2397955166fe35c845f07f5d5a864eac@sha256:691af1d8fab54afd9cb743da2f9a1bbc5fa396f4d11086b2b68a96525ab8b803
          name: container-image
